name: format
on:
  - push
  - pull_request
env:
  golang-version: '1.16'
jobs:
  fmt:
    runs-on: ubuntu-latest
    name: Jsonnet formatter
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.golang-version }}
    - name: Get jsonnet
      run: go get github.com/google/go-jsonnet/cmd/jsonnet@7373f5b6067899549aa7524ca2bba0dff22fe494
    - run: make --always-make fmt && git diff --exit-code
